### Register a new user
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
  "email": "test@gmail.com",
  "password": "Test@1234",
  "firstName": "Kasun",
  "lastName": "Perera",
  "role": "client"
}

### Login
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "email": "test@gmail.com",
  "password": "Test@1234"
}
