export { DashboardHomeComponent } from './lib/dashboard-home/dashboard-home.component';
export { BookingsTodayComponent } from './lib/bookings-today/bookings-today.component';
export { ManageServicesComponent } from './lib/manage-services/manage-services.component';
export { ManageStaffComponent } from './lib/manage-staff/manage-staff.component';
export { DashboardOverviewComponent } from './lib/dashboard-overview/dashboard-overview.component';
export { ManageHoursComponent } from './lib/manage-hours/manage-hours.component';
export { SalonReviewsComponent } from './lib/salon-reviews/salon-reviews.component';
export { RegisterSalonComponent } from './lib/register-salon/register-salon.component';
export { SalonSettingsComponent } from './lib/salon-settings/salon-settings.component';
export { DASHBOARD_ROUTES } from './lib/dashboard.routes';
export { LocationPickerComponent } from './lib/location-picker/location-picker.component';
export type { SelectedLocation } from './lib/location-picker/location-picker.component';
export { SalonImageUploaderComponent } from './lib/salon-images/salon-image-uploader.component';
